name: Build + Deploy

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    # Checkout Code
    - uses: actions/checkout@v2
    
    # Setup npm
    - name: Setup Node.js
      uses: actions/setup-node@v2.1.5 
    - name: Install dependencies
      run: npm install
    - name: Build release
      run: npm run release
      
    # Create Release + Files
    - name: Create GitHub release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload OpenRCT2 Plugin
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./out/CCPlugin.min.js
        asset_name: CCPlugin.js
        asset_content_type: application/javascript
      
    
